### ISSUE TITLE
Add GitHub Action examples for how to use it

### ISSUE THREAD

**Issue by matks** [PrestaShop/php-dev-tools#25]
Following @Matt75 suggestion https://github.com/PrestaShopCorp/psgdpr/pull/87#issuecomment-635382803

**Comment by Quetzacoalt91** [comment]
Example are provided in the devdocs: https://devdocs.prestashop.com/1.7/modules/testing/ci-cd/

Header stamp is not part of it yet, as it does not have any `dry-run` mode
