### ISSUE TITLE
symfony/event-dispatcher must be downgraded

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/php-dev-tools#27]
Actually, if we install this dependency in module, that installs `symfony/event-dispatcher` in version 5.0.

But PrestaShop embed `symfony/event-dispatcher` in 3.4

And that broke modules as install :

![image](https://user-images.githubusercontent.com/1533248/85120972-4c7c4200-b224-11ea-9b1e-91739a7868bd.png)

![image](https://user-images.githubusercontent.com/1533248/85120572-b6e0b280-b223-11ea-9778-4b88e26c8408.png)

**Comment by Progi1984** [comment]
Error from the module.
Thanks @Quetzacoalt91 

> Hey,
> 
> The module dependencies should be loaded when the core ones do not exist. Can you please follow https://devdocs.prestashop.com/1.7/modules/concepts/composer/#setup-composer-in-a-module so your autoloader is placed at the end of the list with `"prepend-autoloader": false`?

**Comment by matks** [comment]
2 questions:
- would it be possible to automaitcally (I'm thinking about CI) find such an error ? maybe install a PS then use CLI command to install the module ?
- we need to update all modules with `"prepend-autoloader": false` AND update the composer.lock, right ?

**Comment by matks** [comment]
Note: using `prepend-autoloader` does not modify composer.lock
