### ISSUE TITLE
Prestashop: FatalThrowableError after installing the dev tools

### ISSUE THREAD

**Issue by gkssjovi** [PrestaShop/php-dev-tools#42]
Hello,

I got this error after installing this package and run composer dump-autoload

If I run composer dump-autoload --no-dev it's fine, but the package is not loaded.

(1/1) FatalThrowableError
Type error: Argument 1 passed to Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher::dispatch() must be an object, string given, called in /Users/gkssjovi/www/prestashop/prestashop_1.7.5.0/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php on line 127

**Comment by matks** [comment]
Hi @gkssjovi, can you explain more the context?

You created a PHP project with a composer.json and added this package as a composer dependency? So your composer.json looks like
```
{
    "name": "...",
    "require": {
        "prestashop/php-dev-tools":"..."
```

**Comment by gkssjovi** [comment]
Hi @matks 
I'm a contributor on prestashop addons website, and I have tried to add the "prestashop/php-dev-tools" package in my composer.json to format and check the code for errors.

Yes I have added the package to the composer.json "require-dev" section.
```
 "require-dev": {
        "prestashop/php-dev-tools": "^3.11",
        "phpstan/phpstan": "^0.12.59"
    }
```

After I run `composer dump-autoload` I have this error to the admin area:

```
(1/1) FatalThrowableErrorType error: Argument 1 passed to Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher::dispatch() must be an object, string given, called in /Users/gkssjovi/www/prestashop/prestashop_1.7.5.0/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php on line 127
--
in TraceableEventDispatcher.php line 131
at TraceableEventDispatcher->dispatch('kernel.request', object(GetResponseEvent))in HttpKernel.php line 127
at HttpKernel->handleRaw(object(Request), 1)in HttpKernel.php line 68
at HttpKernel->handle(object(Request), 1, false)in Kernel.php line 200
at Kernel->handle(object(Request), 1, false)in index.php line 124
```

I have removed the also the cache folders from `prestashop_1.7.5.0/var/cache/dev` and `prestashop_1.7.5.0/var/cache/prod` but the error is still there.

So this is happen only when the package is included into the file `vendor/autload.php`.

I'm working on prestashop 1.7.5.0 but I have tried also on 1.7.7.0 and is the same result.
PHP version ( PHP 7.2.34 (cli) (built: Nov 30 2020 14:13:42) ( NTS ) )

Do you have any suggestions?

Thank you

**Comment by gkssjovi** [comment]
I forgot to mention. The composer.json is placed into the module folder.

**Comment by PierreRambaud** [comment]
Regarding your error, it looks not related to this tool.
I don't understand how the composer.json can be in your module directory, whereas the error message is talking about a prestashop_1.7.5.0. It makes me think you change the original composer.json of your prestashop by adding your own module inside.

**Comment by gkssjovi** [comment]
The composer.json is in my module without modifying the prestashop root composer.json.
Is this not the wright approach to install this tool into the module composer.json file? Should I install it on the root?

**Comment by PierreRambaud** [comment]
yes it's the right way to use this tool. The thing I don't understand is why you talk about `prestashop_1.7.5.0` or why it's related to the `/Users/gkssjovi/www/prestashop/prestashop_1.7.5.0/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php` it's not your module path.

**Comment by gkssjovi** [comment]
But that is happen.

The first autoload working on the second with the dev dependencies I got that error.

Here is the file content with `composer dump-autoload --no-dev`
```

<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'PQNPro\\Validate\\' => array($baseDir . '/classes/Validate'),
    'PQNPro\\Traits\\' => array($baseDir . '/classes/traits'),
    'PQNPro\\TerminalCommand\\' => array($baseDir . '/classes/TerminalCommand'),
    'PQNPro\\ObjectModel\\' => array($baseDir . '/classes/ObjectModel'),
    'PQNPro\\Models\\' => array($baseDir . '/classes/Models'),
    'PQNPro\\Interfaces\\' => array($baseDir . '/classes/Interfaces'),
    'PQNPro\\Controllers\\' => array($baseDir . '/controllers'),
    'PQNPro\\Config\\' => array($baseDir . '/classes/Config'),
    'PQNPro\\Adbar\\' => array($baseDir . '/libraries/php-dot-notation/src'),
    'PQNPro\\' => array($baseDir . '/classes'),
);

```

This is the content with `composer dump-autoload`
```

<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Symfony\\Polyfill\\Php80\\' => array($vendorDir . '/symfony/polyfill-php80'),
    'Symfony\\Polyfill\\Php73\\' => array($vendorDir . '/symfony/polyfill-php73'),
    'Symfony\\Polyfill\\Php72\\' => array($vendorDir . '/symfony/polyfill-php72'),
    'Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'Symfony\\Polyfill\\Intl\\Normalizer\\' => array($vendorDir . '/symfony/polyfill-intl-normalizer'),
    'Symfony\\Polyfill\\Intl\\Grapheme\\' => array($vendorDir . '/symfony/polyfill-intl-grapheme'),
    'Symfony\\Polyfill\\Ctype\\' => array($vendorDir . '/symfony/polyfill-ctype'),
    'Symfony\\Contracts\\Service\\' => array($vendorDir . '/symfony/service-contracts'),
    'Symfony\\Contracts\\EventDispatcher\\' => array($vendorDir . '/symfony/event-dispatcher-contracts'),
    'Symfony\\Component\\String\\' => array($vendorDir . '/symfony/string'),
    'Symfony\\Component\\Stopwatch\\' => array($vendorDir . '/symfony/stopwatch'),
    'Symfony\\Component\\Process\\' => array($vendorDir . '/symfony/process'),
    'Symfony\\Component\\OptionsResolver\\' => array($vendorDir . '/symfony/options-resolver'),
    'Symfony\\Component\\Finder\\' => array($vendorDir . '/symfony/finder'),
    'Symfony\\Component\\Filesystem\\' => array($vendorDir . '/symfony/filesystem'),
    'Symfony\\Component\\EventDispatcher\\' => array($vendorDir . '/symfony/event-dispatcher'),
    'Symfony\\Component\\Console\\' => array($vendorDir . '/symfony/console'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Psr\\EventDispatcher\\' => array($vendorDir . '/psr/event-dispatcher/src'),
    'Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'PrestaShop\\HeaderStamp\\' => array($vendorDir . '/prestashop/header-stamp/src'),
    'PrestaShop\\CodingStandards\\' => array($vendorDir . '/prestashop/php-dev-tools/src'),
    'PhpParser\\' => array($vendorDir . '/nikic/php-parser/lib/PhpParser'),
    'PhpCsFixer\\' => array($vendorDir . '/friendsofphp/php-cs-fixer/src'),
    'PQNPro\\Validate\\' => array($baseDir . '/classes/Validate'),
    'PQNPro\\Traits\\' => array($baseDir . '/classes/traits'),
    'PQNPro\\TerminalCommand\\' => array($baseDir . '/classes/TerminalCommand'),
    'PQNPro\\ObjectModel\\' => array($baseDir . '/classes/ObjectModel'),
    'PQNPro\\Models\\' => array($baseDir . '/classes/Models'),
    'PQNPro\\Interfaces\\' => array($baseDir . '/classes/Interfaces'),
    'PQNPro\\Controllers\\' => array($baseDir . '/controllers'),
    'PQNPro\\Config\\' => array($baseDir . '/classes/Config'),
    'PQNPro\\Adbar\\' => array($baseDir . '/libraries/php-dot-notation/src'),
    'PQNPro\\' => array($baseDir . '/classes'),
    'Doctrine\\Common\\Lexer\\' => array($vendorDir . '/doctrine/lexer/lib/Doctrine/Common/Lexer'),
    'Doctrine\\Common\\Annotations\\' => array($vendorDir . '/doctrine/annotations/lib/Doctrine/Common/Annotations'),
    'Composer\\XdebugHandler\\' => array($vendorDir . '/composer/xdebug-handler/src'),
    'Composer\\Semver\\' => array($vendorDir . '/composer/semver/src'),
);

```

**Comment by gkssjovi** [comment]
I don't understand how it's related but it is :D

**Comment by PierreRambaud** [comment]
Could you provide us a zip containing your module. Or screenshots / videos about how you do it?

**Comment by gkssjovi** [comment]
Sure, I can provide the module and the database for the module.
But can you tell me how to send it in private?

**Comment by gkssjovi** [comment]
Of if you have access to the section https://addons.prestashop.com/en/contact-us on the prestashop addons website, I can post the link to the module download there.

**Comment by PierreRambaud** [comment]
We want to be sure the knowledge is shared, if you have a problem with your module and can't show us everything you have inside, create one without all the code you put inside and be sure the problem is reproducible :)

**Comment by gkssjovi** [comment]
Thank you for the suggestion. I have generated a new module with the prestashop tools.
The issue can be reproduced here.

Steps:

```
composer install
composer dump-autoload --no-dev
```

install the module

then

`composer dump-autload`

The the error happens.

[testmodule.zip](https://github.com/PrestaShop/php-dev-tools/files/5671848/testmodule.zip)

**Comment by PierreRambaud** [comment]
I didn't manage to reproduce the issue:
![image](https://user-images.githubusercontent.com/1462701/101778726-89026980-3af4-11eb-83b9-8bcfb282ba3e.png)

Could you share us a screenshots about what you did?

**Comment by gkssjovi** [comment]
I have uploaded the video to reproduce the error.
The prestashop website is downloaded as .zip file from the official website, is not installed via git clone. I don't know if that is related or not this this issue.

[https://www.youtube.com/watch?v=4pE8A3T2FTw]

**Comment by PierreRambaud** [comment]
The problem doesn't come from this module but how you prepend your autoloader.
https://devdocs.prestashop.com/1.7/modules/concepts/composer/#important-notes

Adding will fix your issue.
```
  "config": {
        "prepend-autoloader": false
    }
```

**Comment by PierreRambaud** [comment]
Thank you for reporting an issue on GitHub, even if the problem doesn't come from this repository, we really appreciate receiving feedbacks from the community.

**Comment by gkssjovi** [comment]
Probably someone will have the same error like me because of the miss attention to the prestashop documentation, it will find the answer here.
Thank you again for your prompt solution and response.

**Comment by gkssjovi** [comment]
I have another question, but it's not related to this problem.

Should I create a .stub file for each prestashop class when I'm using phpstan?

I have called the phpstan like this, but the ObjectModel is not loaded, and I get an error that does not exists.

_PS_ROOT_DIR_=/Users/gkssjovi/www/prestashop/prestashop_1.7.5.0 ./vendor/bin/phpstan --configuration=tests/phpstan/phpstan.neon analyse

Where I should ask some questions for this problem to not polute this thread?
