### ISSUE TITLE
Consider renaming this project

### ISSUE THREAD

**Issue by Quetzacoalt91** [PrestaShop/php-dev-tools#9]
This project won't provide tools only for coding standards, the current name `php-coding-standards` seems too restrictive.

**Comment by Quetzacoalt91** [comment]
*  PrestaShop/php-dev-tools
*  PrestaShop/php-gadgets

**Comment by matks** [comment]
`PrestaShop/php-dev-tools` 👍 

Maybe emphasize the fact this is dedicated to modules => PrestaShop/php-module-dev-tools
This way, if one day we publish dev tools dedicated to shops or themes, there will be no ambiguity

**Comment by PierreRambaud** [comment]
I'm more in favor of `PrestaShop/php-dev-tools` because we can create tools, not related to our modules, but using part of this repository (like cs fixer as example)

**Comment by Quetzacoalt91** [comment]
Indeed, this tools aggregator can be used on any PHP project, not only modules.
